### ISSUE TITLE
About model's inconsistent answer

### ISSUE THREAD

**Issue by sentinel8b** [Q-Future/Co-Instruct#3]
First of all, I appreciate for your amazing works that gives me an idea for my future research.
![image](https://github.com/Q-Future/Co-Instruct/assets/58873463/ed91f60d-08af-48c5-ab92-47463fdc2748)
Like above figure, I asked over/under exposed area of image sequentially. And model answered as I intended.
But when I asked like below. It gives me inconsistent answer ('No over or under exposed part')
![image](https://github.com/Q-Future/Co-Instruct/assets/58873463/15492e01-6503-40a2-b3fd-0c6e989c90b3)

**Comment by teowu** [comment]
Hi! Thank you about this comment.

At present, the model is **not fine-tuned** with complex (i.e. more than one question) instructions, and may experience unexpected behaviour. Similarly, it is also not stable while presenting Chinese or Korean instructions, and might get strange outputs.

We will present a more capable version in the future to handle more diverse instructions.
